# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/todo_db?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect  batch:    job:      enabled: false

# ===============================
# = Logging configurations
# ===============================
logging:  level:
    org.springframework : DEBUG
    org.springframework.boot: info
  
server:  port: 8085

